# -*- coding: utf-8 -*-
"""my_min&front_back.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dy_wg_EcdnXlsHBQMffjVajRT5q2N0eK

#Find the min of the inputted numbers:
Test	
print(my_min(5,6,7))
result 5

print(my_min(3,8,-9,0,12,1.2))
result -9

print(my_min(-100))
result -100
"""

def my_min(*num):
  mi = num[0]
  for i in num:
    if i<mi:
      mi = i
  return mi
print(my_min(3,8,-9,0,12,1.2))

"""Given a string, return a new string where the first and last chars have been exchanged.


print(front_back('clarusway'))
output: ylaruswac

print(front_back('ab')) 
output: ba
"""

def front_back(word):
  if len(word)<=1:
    return word
  return word[-1] + word[1:-1] + word[0]
print(front_back('clarusway'))